language: node_js
sudo: true
node_js: 4
before_deploy:
- npm install -g bower
- bower install
- gem install scss_lint
deploy:
  provider: script
  script:
  - npm run deploy
  on:
    branch: master
    repo: watson-developer-cloud/ui-components
  skip_cleanup: true
notifications:
  email: false
env:
  global:
  - secure: DA5poR93tCCKG4/0R/4BaR6paFDExAZ3nbTUnzoyogWPxGwjfTXtMwQxMgd9a63hZX0VRdPqYIPTl0ZHQKWB9aJ5xAF7sOMt+91pxaTcNnVvHo3NobK5miJrWWlqpcUppJiNAq1ZTSOcfWI7Eeql4zJiBsCjtvZbRCgic3qeMW+CZgxzs1ZEPJJobybBmuZoZOXniyahEvdYUpZss3xJuQM2xZJR1YWvm40KgHfOaOOPQjc78tjNxuzqkv1s310WCk+loMfHL+kzQ2cZq2gu+Q6PipB02EpZI5QMSirrfwndX4Uu8ERZqzNDzk/tjK4qeE7EjnpVgte+18uCvmyLhGSzdMLKhsDhPoeevkwQVf6jX6J8ja4IVWEbNpVD1aBd+YLJPnceiXmU3PvNmu4muqy9mpXysukURF9pZU61Y9Dv8mRMAjAJWWqiGyQ0NTRjyTKe9I6ba9BqGRYUXqHD+6jZNyuryGHhYxXP3RRGKI9+pIAikORdvB+NvTJsxxZwskl8IRPMI0LusZ3OkrDFz9Pk3KDTt93tsb8nr3R4t55A2gurxEL8aW4LhDUNNutaPbNwg8OIyCXTzauI2chDU61wczexdMDQ1y3EP5OYZ1S3PawctZYf0yM80/0ybvcwornIJSsVW1roapvSk0EAZFm1hIGloXe43JA8njmaZ3w=
