language: node_js
sudo: true
node_js: 4
before_deploy:
- npm install -g bower
- bower install
- gem install scss_lint
deploy:
  provider: script
  script:
  - npm run deploy
  on:
    branch: master
    repo: jzhang300/ui-components
  skip_cleanup: true
notifications:
  email: false
env:
  global:
    secure: UH2brgYIsMYb+6ctwFMlVsBxBj3+N7trFD1XRL4s8mj5HfvQRHEKyu/sg94As/JfsQBQd7nEdd22/68ETZ93cKvWmt3InVOFWQ7e9/nsQrL05EAntrwL55meO+a6iSUyzawsBzB9tcUO5b5XPfprW5iLepWShi4hc3i6qnTwseTBtWdeVomM9+i8nQtyBgmAoj/TbJnt8ye6Bu87iEhUyKeR3i1gmxfNsrwJSYj5ICi7UVPPJ6g+oCEnjlQXc+YTdecM0qBaM2pv9KGEc6wJKckWlPG/kLgNbj0BSoU+q8edUev5KfO4MPv4BgF9IW/UEe4cIskCNsQUgvBrthZIRipoy3/Z/2Pjf2IUusr1RcyUc/fU8GiKI/Wvf43CAm/lbno8YeO+wmLErQS98HHMeQyE4D1IvrZMTqCLhqx0Iq+rOPicWlsPI+PiEOFien26gACLHMQPF2gZ1xmLsGYd1dHr6ivRIJIXurWccnj3vWLc08rl5pOdIzol+PslFp8qG3MhtPrDF9/vb0WbPfsBEpdV99/LUGUzFJxs8TyAsEu7AYzN6xHgo8q3g7mNhyNp1OPZcAihB3aZQ0O3tasx8V+5jhXSC+DFnV+8dt1pXRw1x4zNBMe6HUl6VLEt3RycfSpkNKdH58vzUoiw23oqJ0HjiPMWR5DDHaNMKb5ug7g=
