language: node_js
sudo: true
node_js: 4
script: npm run lint
deploy:
  provider: script
  script:
  - npm run deploy
  on:
    branch: master
    repo: watson-developer-cloud/ui-components
  skip_cleanup: true
notifications:
  email: false
env:
  global:
  - secure: Bd805RBfKwm8ikfCKW4dcrz1gPtTN1pwnQ8eayQ6soI4nfD9PlJ+TcbAaGTScIr9X0rj9SR1bNxVscdwiGbb43NizyFikm75y70ox5nrEH7RVKex43P977kiqy2F7iMr9RC2it7wDz8BPe5Gya1Jjkb2QIDSo+U0L74K78LLoocIf1UA70kabIyYcyQkvIox0D/KW/B+/82jr2QTu7hZHxkxfuq/J5YmY5CEPG3aeF2hWhZ+tPCPpEyixWj3hccdG+l362RlWdD0a63HCKn34O4EejgPlY3RRTNeRo/m3HKCbqT4E26J98tkuFboPlcY2lVZKilEMSsb3M1GsfUsXJERUPk9SpK6hxPIg9S2ORqFV21uRLvGXkqD/aYlkbKgZLcqmiDxiAHTc04nI0ZDfuB/6scsQFbFpxPVdZXmbRb6pmVHsY/XGlA4Dkqi90uNH20ycV8Vci2X5jtA+PGcWWkKXvGHJ57aoRhGHp1DfFI6pRq4bGVEaWvlxXuaK38RXrKVwNtRlRjkJ08jYLNo3rhHKlBZWXuH/Y9WhoAKrpj7rUsn5pAG0JDReUruMznfyglFADCoFxP4fAVrLSk2h3DslX3vNedAp/WQpf7hnN2ockAt0D7vpA5KYuzr2cLCdDs64VglrJCxEefwP92FoFcgTg7SbdesLW2P58F3Akc=
